# Site settings
title: Open-TEE
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Open-TEE Virtual Trusted Execution Environment
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://open-tee.github.io/" # the base hostname & protocol for your site
github_username:  Open-TEE

# Build settings
markdown: kramdown
exclude: [vendor]
